cm.model.types = {
    "CM_Model_Language": 5,
    "CM_Model_Location": 6,
    "CM_Model_Splitfeature": 7,
    "CM_Model_Splittest": 8,
    "CM_Model_SplittestVariation": 9,
    "CM_Model_User": 10,
    "CM_Model_Splittest_RequestClient": 11,
    "CM_Model_Splittest_User": 12,
    "CM_Model_Stream_Publish": 13,
    "CM_Model_Stream_Subscribe": 14,
    "CM_Model_StreamChannel_Message": 15,
    "CM_Model_StreamChannel_Message_User": 17,
    "Denkmal_Model_Event": 28,
    "Denkmal_Model_Link": 29,
    "Denkmal_Model_Song": 31,
    "Denkmal_Model_User": 32,
    "Denkmal_Model_Venue": 33,
    "Denkmal_Model_VenueAlias": 34,
    "CM_Model_Location_City": 39,
    "CM_Model_Location_Country": 40,
    "CM_Model_Location_State": 41,
    "CM_Model_Location_Zip": 42,
    "CM_Model_LanguageKey": 43,
    "Denkmal_Scraper_SourceResult": 51,
    "Denkmal_Model_UserInvite": 61,
    "Denkmal_Push_Subscription": 63,
    "Denkmal_Push_Notification_Message": 64,
    "CM_Model_Currency": 65,
    "CM_Model_StreamChannel_Media": 70,
    "CM_Model_StreamChannelArchive_Media": 71,
    "CM_StreamChannel_Thumbnail": 72,
    "Denkmal_Model_Region": 77,
    "CM_Janus_StreamChannel": 83,
    "Denkmal_Model_FacebookPage": 87,
    "CM_Migration_Model": 90,
    "Denkmal_Model_EventLink": 91
};
cm.action.types = {
    "CM_Action_Email": 3
};
